# Generated by Django 5.0.6 on 2025-05-23 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0004_expensecategory_payment_due_date_alter_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extraclasssession',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='extraclass',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='extraclasssession',
            name='session_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='extraclasssession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.student'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
    ]
