# Generated by Django 5.0.6 on 2025-05-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0005_alter_extraclasssession_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='allergy_details',
            field=models.CharField(blank=True, help_text='Specify the allergy details if applicable.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='has_allergy',
            field=models.BooleanField(default=False),
        ),
    ]
