# Generated by Django 5.0.6 on 2025-05-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0006_student_allergy_details_student_has_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_completion',
            field=models.DateField(blank=True, help_text='The date when the student will graduate, after which they will be automatically deactivated.', null=True),
        ),
    ]
